# Week 2 — The model is just a rule you can read

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/00Bhuwan/flyrank-ml-internship-my-work/blob/main/notebooks/02_your_first_readable_model.ipynb)

You'll:
1. Write a **1-line hand rule** and rank pages with it.
2. Fit a **depth-2 decision tree** and `print` it — the model "learned" a readable if/else. Then compare — where does it beat your rule, and where doesn’t it?
3. See **why you never feed the outcome back in** — that's leakage.

The payoff isn't a high score. It's: *my intuition was rough, the model found the real signal, and I can read exactly what it found.*

## 0. Setup (Colab or local)

In [1]:
import os, sys, subprocess

IN_COLAB = "google.colab" in sys.modules
REPO_URL = "https://github.com/flyrank-bih/flyrank-ml-internship-starter"
REPO_DIR = "flyrank-ml-internship-starter"

if IN_COLAB:
    if not os.path.isdir(REPO_DIR):
        subprocess.run(["git", "clone", "--depth", "1", REPO_URL, REPO_DIR], check=True)
    os.chdir(REPO_DIR)
    subprocess.run([sys.executable, "-m", "pip", "install", "-q", "-r", "requirements.txt"], check=True)
elif os.path.basename(os.getcwd()) == "notebooks":
    os.chdir("..")

import pandas as pd, numpy as np
df = pd.read_csv("data/raw/content_refresh_anonymized.csv")

# The label: a page is 'declining' when its recent trend is down. Simple, honest starter label.
df["is_declining_label"] = df["trend_direction"].str.lower().eq("down").astype(int)
print(df.shape[0], "pages |  declining rate:", round(df["is_declining_label"].mean(), 3))

30000 pages |  declining rate: 0.542

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 46 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   content_id              30000 non-null  object
 1   client_id               30000 non-null  object
 2   search_volume           27532 non-null  float64
 3   competition             27532 non-null  float64
 4   competition_level       27390 non-null  object
 5   cpc                     27532 non-null  float64
 6   content_type            30000 non-null  object
 7   main_intent             27626 non-null  object
 8   word_count              22301 non-null  float64
 9   char_count              22301 non-null  float64
 10  provider_used           8562 non-null   object
 11  model_used              24267 non-null  object
 12  impressions_90d         30000 non-null  int64
 13  clicks_90d              30000 non-null  int64
 14  pageviews_90d           30000 non-null  int64
 15  sessions_90d            30000 non-null  int64
 16  users_90d               30000 non-null  int64
 17  engaged_sessions_90d    30000 non-null  int64
 18  ai_sessions_90d         30000 non-null  int64
 19  scroll_events_90d       30000 non-null  int64
 20  days_with_impressions   30000 non-null  int64
 21  days_with_sessions      30000 non-null  int64
 22  impressions_last_30d    30000 non-null  int64
 23  clicks_last_30d         30000 non-null  int64
 24  sessions_last_30d       30000 non-null  int64
 25  impressions_prev_30d    30000 non-null  int64
 26  clicks_prev_30d         30000 non-null  int64
 27  sessions_prev_30d       30000 non-null  int64
 28  content_age_days        30000 non-null  int64
 29  age_tier                30000 non-null  object
 30  age_tier_order          30000 non-null  int64
 31  days_since_last_update  30000 non-null  int64
 32  freshness_tier          30000 non-null  object
 33  word_count_tier         22301 non-null  object
 34  char_count_tier         22301 non-null  object
 35  ctr                     30000 non-null  float64
 36  avg_position            30000 non-null  float64
 37  engagement_rate         30000 non-null  float64
 38  scroll_rate             29875 non-null  float64
 39  ai_traffic_pct          30000 non-null  float64
 40  impression_tier         30000 non-null  object
 41  position_tier           30000 non-null  object
 42  trend_direction         30000 non-null  object
 43  trend_pct               26612 non-null  float64
 44  is_declining_label      30000 non-null  int64
 45  hand_rule_score         30000 non-null  int64
dtypes: float64(11), int64(21), object(14)
memory usage: 10.5+ MB

In [11]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
search_volume,27532.0,158.882391,1518.270825,0.0,0.0,10.00,20.00,74000.00
competition,27532.0,0.146954,0.285241,0.0,0.0,0.00,0.13,1.00
cpc,27532.0,0.485342,2.101560,0.0,0.0,0.00,0.00,100.36
word_count,22301.0,3107.760325,1452.382598,8.0,2413.0,2877.00,3666.00,9546.00
char_count,22301.0,20665.277835,10115.344042,40.0,15644.0,19116.00,24011.00,111158.00
impressions_90d,30000.0,5200.366300,16838.019547,1.0,81.0,731.00,3615.25,517715.00
clicks_90d,30000.0,16.097333,75.076958,0.0,0.0,1.00,7.00,4178.00
pageviews_90d,30000.0,49.942467,152.101430,0.0,2.0,8.00,33.00,5998.00
sessions_90d,30000.0,37.066633,107.069131,1.0,2.0,7.00,27.00,4345.00
users_90d,30000.0,35.937700,103.748185,1.0,2.0,7.00,27.00,4913.00
engaged_sessions_90d,30000.0,0.991933,4.359576,0.0,0.0,0.00,1.00,290.00
ai_sessions_90d,30000.0,0.204500,1.363601,0.0,0.0,0.00,0.00,64.00
scroll_events_90d,30000.0,4.033500,22.335179,0.0,0.0,1.00,3.00,2605.00
days_with_impressions,30000.0,61.454033,32.689245,1.0,31.0,81.00,88.00,88.00
days_with_sessions,30000.0,13.096333,17.307759,1.0,2.0,6.00,16.00,90.00
impressions_last_30d,30000.0,1429.058733,5643.852081,0.0,10.0,139.00,768.00,238796.00
clicks_last_30d,30000.0,4.933867,23.929393,0.0,0.0,0.00,2.00,1176.00
sessions_last_30d,30000.0,14.114267,39.036371,0.0,0.0,3.00,12.00,1081.00
impressions_prev_30d,30000.0,1783.078500,6150.429511,0.0,19.0,210.00,1143.00,218786.00
clicks_prev_30d,30000.0,5.435100,28.358673,0.0,0.0,0.00,2.00,1627.00
sessions_prev_30d,30000.0,10.283000,42.578003,0.0,1.0,2.00,7.00,4247.00
content_age_days,30000.0,256.167800,132.707930,90.0,132.0,236.00,333.00,564.00
age_tier_order,30000.0,4.786533,0.790392,3.0,4.0,5.00,5.00,6.00
days_since_last_update,30000.0,46.098300,42.078709,1.0,20.0,20.00,104.00,373.00
ctr,30000.0,0.510733,3.279162,0.0,0.0,0.07,0.29,100.00
avg_position,30000.0,16.342380,15.216790,0.0,6.2,10.80,22.30,245.00
engagement_rate,30000.0,2.534520,8.310096,0.0,0.0,0.00,1.35,100.00
scroll_rate,29875.0,18.212921,29.472768,0.0,0.0,5.00,23.53,300.00
ai_traffic_pct,30000.0,0.768196,7.429454,0.0,0.0,0.00,0.00,300.00
trend_pct,26612.0,-4.785969,473.861780,-100.0,-62.6,-33.50,0.00,44900.00
is_declining_label,30000.0,0.542067,0.498236,0.0,0.0,1.00,1.00,1.00
hand_rule_score,30000.0,6.573700,528.117366,0.0,0.0,0.00,0.00,61678.00

In [13]:
df.sample(5).T

,19595,877,21281,3124,3978
content_id,content_0bfb89290c3c,content_33f39767de6c,content_db2235d35a88,content_5ecb89199ba2,content_2f0d3803995d
client_id,client_19581e27de,client_f369cb89fc,client_349c41201b,client_6208ef0f77,client_349c41201b
search_volume,40.0,0.0,10.0,0.0,0.0
competition,0.0,0.0,0.43,0.0,0.0
competition_level,LOW,LOW,MEDIUM,LOW,LOW
cpc,0.0,0.0,0.06,0.0,0.0
content_type,keyword article,keyword article,keyword article,keyword article,keyword article
main_intent,transactional,informational,informational,commercial,informational
word_count,3002.0,2935.0,3083.0,7521.0,3830.0
char_count,20463.0,17470.0,19525.0,48622.0,25438.0
provider_used,google,NaN,google,NaN,NaN
model_used,gemini-3-flash-preview,gemini-2.5-flash,gemini-3-flash-preview,gemini-3-flash-preview,gemini-3-flash-preview
impressions_90d,110,12,167,4669,5889
clicks_90d,0,0,0,24,18
pageviews_90d,2,1,3,254,27
sessions_90d,2,1,3,135,27
users_90d,2,1,3,132,24
engaged_sessions_90d,0,0,0,2,1
ai_sessions_90d,0,0,0,2,0
scroll_events_90d,0,0,0,2,1
days_with_impressions,42,8,64,87,88
days_with_sessions,2,1,3,44,20
impressions_last_30d,10,11,25,2788,1521
clicks_last_30d,0,0,0,8,5
sessions_last_30d,1,0,1,91,11
impressions_prev_30d,85,0,50,1247,1943
clicks_prev_30d,0,0,0,8,5
sessions_prev_30d,1,0,2,29,8
content_age_days,112,187,104,229,148
age_tier,91-180,181-365,91-180,181-365,91-180
age_tier_order,4,5,4,5,4
days_since_last_update,20,20,20,104,8
freshness_tier,0-30,0-30,0-30,91-180,0-30
word_count_tier,2000-3500,2000-3500,2000-3500,3500+,3500+
char_count_tier,15000-25000,15000-25000,15000-25000,25000+,25000+
ctr,0.0,0.0,0.0,0.51,0.31
avg_position,8.2,45.3,11.2,16.1,19.1
engagement_rate,0.0,0.0,0.0,1.48,3.7
scroll_rate,0.0,0.0,0.0,0.79,3.7
ai_traffic_pct,0.0,0.0,0.0,1.48,0.0
impression_tier,low,low,low,good,good
position_tier,page_1,page_3_5,striking,striking,striking
trend_direction,down,new,down,up,down
trend_pct,-88.2,NaN,-50.0,123.6,-21.7
is_declining_label,1,0,1,0,1
hand_rule_score,0,0,0,0,0

## 1. A rule you write by hand: `stale x visible`
Intuition: a page worth reviewing is one that is **stale** (not updated in a while) **and** still **visible** (getting impressions). Rank those by how much exposure they have.

In [2]:
stale   = (df["days_since_last_update"] >= 180).astype(int)
visible = (df["impressions_90d"] >= 500).astype(int)
df["hand_rule_score"] = stale * visible * df["impressions_90d"]

top10 = df.sort_values("hand_rule_score", ascending=False).head(10)
top10[["impressions_90d", "days_since_last_update", "avg_position", "ctr", "trend_direction"]]

,impressions_90d,days_since_last_update,avg_position,ctr,trend_direction
16751,61678,194,19.7,0.15,down
16514,59472,194,24.8,0.13,down
7021,25715,194,22.2,0.23,down
21268,13299,193,10.5,0.49,down
11489,7812,194,39.0,0.01,down
12045,7558,193,17.9,0.20,down
698,4590,194,31.0,0.00,down
5327,4556,194,16.4,0.33,down
26810,4429,194,25.3,0.38,down
20837,1697,193,15.8,0.12,down

We need a way to score any ranking. **Precision@K** = of the top K pages a ranking flags, what fraction are actually declining.

In [3]:
def precision_at_k(scores, labels, k):
    order = np.argsort(-np.asarray(scores))
    topk = np.asarray(labels)[order[:k]]
    return topk.mean()

y = df["is_declining_label"].values
for k in (20, 50):
    print(f"Hand rule  Precision@{k}: {precision_at_k(df['hand_rule_score'], y, k):.3f}")

Hand rule  Precision@20: 0.900
Hand rule  Precision@50: 0.680

## 2. Let a model learn the rule — then read it
A **depth-2 decision tree** can only ask 3 yes/no questions. That constraint is the point: whatever it learns, you can read.

We give it a few **pre-decision** signals — never product flags.

In [4]:
from sklearn.tree import DecisionTreeClassifier, export_text

features = ["content_age_days", "days_since_last_update", "impressions_90d",
            "avg_position", "ctr", "word_count"]
X = df[features].replace([np.inf, -np.inf], np.nan).fillna(0)

tree = DecisionTreeClassifier(max_depth=2, class_weight="balanced", random_state=42)
tree.fit(X, y)

print(export_text(tree, feature_names=features))

|--- impressions_90d <= 5.50
|   |--- avg_position <= 0.75
|   |   |--- class: 0
|   |--- avg_position >  0.75
|   |   |--- class: 0
|--- impressions_90d >  5.50
|   |--- content_age_days <= 312.50
|   |   |--- class: 1
|   |--- content_age_days >  312.50
|   |   |--- class: 0

That printout **is** the model — a human-readable if/else. Now rank pages by the tree's probability and score it the same way.

In [5]:
tree_score = tree.predict_proba(X)[:, 1]
for k in (20, 50):
    hr = precision_at_k(df["hand_rule_score"], y, k)
    tr = precision_at_k(tree_score, y, k)
    print(f"Precision@{k}:  hand rule {hr:.3f}   vs   tree {tr:.3f}")

Precision@20:  hand rule 0.900   vs   tree 0.550
Precision@50:  hand rule 0.680   vs   tree 0.600

Look closely: the tree **wins at Precision@50** but your hand rule **wins at Precision@20**. Both results are real. A sharp human rule can be excellent at the very top of the list; the model's advantage shows up deeper, where simple rules run out of signal. Saying exactly that — instead of "the model is better" — is what honest evaluation sounds like.

## 3. Why you can't feed the outcome back in
Your label is `trend_direction == "down"`, and `trend_pct` is the exact percentage change that bucket is computed from — so it **is** the answer in disguise. Watch what happens if you feed it in as a feature:

In [6]:
X_leaky = df[features + ["trend_pct"]].replace([np.inf, -np.inf], np.nan).fillna(0)
leaky = DecisionTreeClassifier(max_depth=2, class_weight="balanced", random_state=42).fit(X_leaky, y)
print(f"'Leaky' tree Precision@50: {precision_at_k(leaky.predict_proba(X_leaky)[:,1], y, 50):.3f}  <- looks amazing")
print(export_text(leaky, feature_names=features + ["trend_pct"]))

'Leaky' tree Precision@50: 1.000  <- looks amazing
|--- trend_pct <= -20.05
|   |--- word_count <= 212.00
|   |   |--- class: 1
|   |--- word_count >  212.00
|   |   |--- class: 1
|--- trend_pct >  -20.05
|   |--- trend_pct <= -19.95
|   |   |--- class: 0
|   |--- trend_pct >  -19.95
|   |   |--- class: 0

The tree just split on `trend_pct` and nailed the label — because the label is **derived from** `trend_pct`. That's **leakage**: the feature is the answer in disguise, and it teaches you nothing.

That's also why the starter data ships **only observable signals** — the product's own decision flags (health scores, "needs CTR fix", and so on) aren't included, so you can't accidentally train on them. You build from what was knowable *before* the outcome.

> Rule of thumb: if a feature would only be known *because someone already made the decision you're predicting*, it leaks. Leave it out.

## 4. 🔧 Your turn
- Change `max_depth` to 3 or 4 — does Precision@50 improve? Can you still read the tree?
- Swap in different features (drop `impressions_90d`, add `engagement_rate`). What does the tree choose to split on first?
- **Important caveat:** we scored *in-sample* here for teaching. The real pipeline uses **client-holdout** validation (`scripts/03_train_model.py`) so a client's pages never appear in both train and test. Re-run your comparison with a train/test split and see if the gap holds.

Write your experiment below.

# Change max_depth to 3 or 4 — does Precision@50 improve? Can you still read the tree?

In [16]:
decide_1 = DecisionTreeClassifier(max_depth=3, class_weight="balanced", random_state=42).fit(X, y)
print(f"'Leaky' tree Precision@50: {precision_at_k(decide_1.predict_proba(X)[:,1], y, 50):.3f}  <- looks amazing")
print(export_text(decide_1, feature_names=features))

'Leaky' tree Precision@50: 0.720  <- looks amazing
|--- impressions_90d <= 5.50
|   |--- avg_position <= 0.75
|   |   |--- impressions_90d <= 3.50
|   |   |   |--- class: 0
|   |   |--- impressions_90d >  3.50
|   |   |   |--- class: 0
|   |--- avg_position >  0.75
|   |   |--- content_age_days <= 108.50
|   |   |   |--- class: 0
|   |   |--- content_age_days >  108.50
|   |   |   |--- class: 0
|--- impressions_90d >  5.50
|   |--- content_age_days <= 312.50
|   |   |--- ctr <= 0.33
|   |   |   |--- class: 1
|   |   |--- ctr >  0.33
|   |   |   |--- class: 1
|   |--- content_age_days >  312.50
|   |   |--- avg_position <= 25.15
|   |   |   |--- class: 0
|   |   |--- avg_position >  25.15
|   |   |   |--- class: 0

In [17]:
decide_2 = DecisionTreeClassifier(max_depth=4, class_weight="balanced", random_state=42).fit(X, y)
print(f"'Leaky' tree Precision@50: {precision_at_k(decide_2.predict_proba(X)[:,1], y, 50):.3f}  <- looks amazing")
print(export_text(decide_2, feature_names=features))

'Leaky' tree Precision@50: 0.680  <- looks amazing
|--- impressions_90d <= 5.50
|   |--- avg_position <= 0.75
|   |   |--- impressions_90d <= 3.50
|   |   |   |--- word_count <= 687.00
|   |   |   |   |--- class: 0
|   |   |   |--- word_count >  687.00
|   |   |   |   |--- class: 0
|   |   |--- impressions_90d >  3.50
|   |   |   |--- content_age_days <= 237.50
|   |   |   |   |--- class: 0
|   |   |   |--- content_age_days >  237.50
|   |   |   |   |--- class: 0
|   |--- avg_position >  0.75
|   |   |--- content_age_days <= 108.50
|   |   |   |--- days_since_last_update <= 14.00
|   |   |   |   |--- class: 1
|   |   |   |--- days_since_last_update >  14.00
|   |   |   |   |--- class: 0
|   |   |--- content_age_days >  108.50
|   |   |   |--- impressions_90d <= 2.50
|   |   |   |   |--- class: 0
|   |   |   |--- impressions_90d >  2.50
|   |   |   |   |--- class: 0
|--- impressions_90d >  5.50
|   |--- content_age_days <= 312.50
|   |   |--- ctr <= 0.33
|   |   |   |--- impressions_90d <= 73.50
|   |   |   |   |--- class: 1
|   |   |   |--- impressions_90d >  73.50
|   |   |   |   |--- class: 1
|   |   |--- ctr >  0.33
|   |   |   |--- impressions_90d <= 24.50
|   |   |   |   |--- class: 0
|   |   |   |--- impressions_90d >  24.50
|   |   |   |   |--- class: 1
|   |--- content_age_days >  312.50
|   |   |--- avg_position <= 25.15
|   |   |   |--- impressions_90d <= 4028.50
|   |   |   |   |--- class: 1
|   |   |   |--- impressions_90d >  4028.50
|   |   |   |   |--- class: 0
|   |   |--- avg_position >  25.15
|   |   |   |--- word_count <= 1027.00
|   |   |   |   |--- class: 0
|   |   |   |--- word_count >  1027.00
|   |   |   |   |--- class: 0

Here, viewing both the depth value of 3 and 4 we can clearly see the range of decision paramaters for narrowing the output. But, as seen above in results the tradeoff remains the dead branches i.e with value 0, while it helps narrow the results the reading becomes complex with unnecessary decision paramaters added.

# Swap in different features (drop impressions_90d, add engagement_rate). What does the tree choose to split on first?

In [22]:
features_new = ['content_age_days',
 'days_since_last_update',
 'engagement_rate',
 'avg_position',
 'ctr',
 'word_count']

X_new = df[features_new].replace([np.inf, -np.inf], np.nan).fillna(0)

tree_new = DecisionTreeClassifier(max_depth=2, class_weight="balanced", random_state=42)
tree_new.fit(X_new, y)

print(export_text(tree_new, feature_names=features_new))

|--- avg_position <= 0.55
|   |--- avg_position <= 0.15
|   |   |--- class: 0
|   |--- avg_position >  0.15
|   |   |--- class: 0
|--- avg_position >  0.55
|   |--- content_age_days <= 287.50
|   |   |--- class: 1
|   |--- content_age_days >  287.50
|   |   |--- class: 0

|--- impressions_90d <= 5.50   
|   |--- avg_position <= 0.75   
|   |   |--- class: 0  
|   |--- avg_position >  0.75  
|   |   |--- class: 0  
|--- impressions_90d >  5.50  
|   |--- content_age_days <= 312.50  
|   |   |--- class: 1  
|   |--- content_age_days >  312.50  
|   |   |--- class: 0

Using the engagement_rate the tree choose to split based on avg_postion and again it splits using avg_position which conflicts with working of decision tree.

# Important caveat: we scored in-sample here for teaching. The real pipeline uses client-holdout validation (scripts/03_train_model.py) so a client's pages never appear in both train and test. Re-run your comparison with a train/test split and see if the gap holds.

In [26]:
# df['client_id'].unique()
test_client = ["client_349c41201b"]
is_test = df["client_id"].isin(test_client)

In [29]:
new_features = ["content_age_days", "days_since_last_update", "impressions_90d",
            "avg_position", "ctr", "word_count"]
new_X = df[new_features].replace([np.inf, -np.inf], np.nan).fillna(0)

X_train, X_test = new_X[~is_test], new_X[is_test]
y_train, y_test = y[~is_test], y[is_test]

In [30]:
tree = DecisionTreeClassifier(max_depth=3, class_weight="balanced", random_state=42)
tree.fit(X_train, y_train)

print(export_text(tree, feature_names=new_features))

|--- impressions_90d <= 5.50
|   |--- avg_position <= 0.75
|   |   |--- impressions_90d <= 3.50
|   |   |   |--- class: 0
|   |   |--- impressions_90d >  3.50
|   |   |   |--- class: 0
|   |--- avg_position >  0.75
|   |   |--- content_age_days <= 108.50
|   |   |   |--- class: 0
|   |   |--- content_age_days >  108.50
|   |   |   |--- class: 0
|--- impressions_90d >  5.50
|   |--- content_age_days <= 312.50
|   |   |--- ctr <= 0.33
|   |   |   |--- class: 1
|   |   |--- ctr >  0.33
|   |   |   |--- class: 1
|   |--- content_age_days >  312.50
|   |   |--- avg_position <= 25.25
|   |   |   |--- class: 0
|   |   |--- avg_position >  25.25
|   |   |   |--- class: 0

In [31]:
# Get predictions for the unseen test data
tree_test_score = tree.predict_proba(X_test)[:, 1]

# Get the hand rule scores for that same test data slice to compare
hand_rule_test_score = df.loc[is_test, "hand_rule_score"]

# Re-run your Precision comparison
for k in (20, 50):
    # Adjust K if your test client has fewer than 50 pages total
    if len(y_test) >= k:
        hr = precision_at_k(hand_rule_test_score, y_test, k)
        tr = precision_at_k(tree_test_score, y_test, k)
        print(f"Out-of-Sample Precision@{k}:  hand rule {hr:.3f}   vs   tree {tr:.3f}")

Out-of-Sample Precision@20:  hand rule 0.750   vs   tree 0.800
Out-of-Sample Precision@50:  hand rule 0.600   vs   tree 0.780

As compared to the previous sample data where tree was underperforming compared to hand rule, In the real client trained model the tree is performing better compared to hand rule i.e handrule 0.750 vs tree 800 in sample of 20 and even better with sample 50.

### Save your work
**Colab:** *File → Save a copy in GitHub* (your submission) and *File → Save a copy in Drive*.

You now have the two core reflexes of applied ML: **discover before you model**, and **prefer a model you can read and can't fool**. That's the whole foundation the capstone builds on.